version: "3"
services:

  vault:
    image: hashicorp/vault
    restart: unless-stopped
    ports:
      - 8200:8200
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "1234567890"
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "1234567890"

  vault_init:
    image: hashicorp/vault
    command: ["/vault-init.sh"]
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "1234567890"
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "1234567890"
    volumes:
      - ./../../../scripts/vault-init.sh:/vault-init.sh
      - certs:/certs
    depends_on:
      - vault

volumes:
  certs: